// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ApiHeroUI.Bootstrap.View = (function(superClass) {
  extend(View, superClass);

  function View() {
    return View.__super__.constructor.apply(this, arguments);
  }

  View.prototype.show = function() {
    this.$el.addClass('show').removeCLass('hidden');
    return this;
  };

  View.prototype.hide = function() {
    this.$el.addClass('hidden').removeCLass('show');
    return this;
  };

  View.prototype.setTooltip = function(text, opts) {
    if (opts == null) {
      opts = {};
    }
    this.$el.toolTip(_.extend(opts, {
      title: text
    }));
    return this;
  };

  View.prototype.pullLeft = function() {
    return this.$el.addClass('pull-left');
  };

  View.prototype.pullRight = function() {
    return this.$el.addClass('pull-right');
  };

  return View;

})(ApiHeroUI.core.View);
